[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "npm install ajv@^8.12.0 ajv-keywords@^4.1.0 ajv-formats@^2.1.1 --legacy-peer-deps --save"
]

[phases.build]
cmds = ["npm ci --legacy-peer-deps && npm run build"]

[start]
cmd = "npm start"

