[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "npm install ajv@6.12.6 ajv-keywords@3.5.2 ajv-formats@1.4.0 --legacy-peer-deps --save-exact"
]

[phases.build]
cmds = ["npm ci --legacy-peer-deps && npm run build"]

[start]
cmd = "npm start"

